name: "Release Milestone"
description: "Template for creating a release milestone with tasks and statuses"
labels:
  - "release-milestone"
assignees: []
body:
  # Text input for "Release Milestone"
  - type: input
    attributes:
      label: "Release Milestone"
      description: "Enter the release milestone name."
      placeholder: "Enter milestone name"
      
  # Text input for "Application"
  - type: input
    attributes:
      label: "Application"
      description: "Enter the name of the application."
      placeholder: "Enter application name"
      
  # Text input for "Target Date"
  - type: input
    attributes:
      label: "Target Date"
      description: "Enter the target release date."
      placeholder: "Enter target release date"

  ## Tasks & Activities with "Assigned to" as Textbox and "Status" as Checkboxes
  
  ### 1) Create Rally milestone and ServiceNow Release:
  - type: markdown
    attributes:
      value: |
        **Assigned to (Rally milestone):** [Enter person assigned]  
        **Status (Rally milestone):** [Complete/In Progress/NA]

  - type: checkboxes
    attributes:
      label: "Status (Rally milestone)"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"
        
  ### 2) QA Sign Off:
  - type: markdown
    attributes:
      value: |
        **Assigned to (QA Sign Off):** [Enter person assigned]  
        **Status (QA Sign Off):** [Complete/In Progress/NA]

  - type: checkboxes
    attributes:
      label: "Status (QA Sign Off)"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"

  ### 3) SRE Signoff:
  - type: markdown
    attributes:
      value: |
        **Assigned to (SRE Signoff):** [Enter person assigned]  
        **Status (SRE Signoff):** [Complete/In Progress/NA]

  - type: checkboxes
    attributes:
      label: "Status (SRE Signoff)"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"

  ### 4) App Owner Approval:
  - type: markdown
    attributes:
      value: |
        **Assigned to (App Owner Approval):** [Enter person assigned]  
        **Status (App Owner Approval):** [Complete/In Progress/NA]

  - type: checkboxes
    attributes:
      label: "Status (App Owner Approval)"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"
