name: "Release Milestone Template"
description: "Template for tracking release milestones and associated tasks"
labels:
  - "release-milestone"
assignees: []
body:
  # General Release Information
  - type: input
    attributes:
      label: "Release Milestone"
      description: "Enter the release milestone name."
      placeholder: "Enter milestone name"

  - type: input
    attributes:
      label: "Application"
      description: "Enter the application name."
      placeholder: "Enter application name"

  - type: input
    attributes:
      label: "Target Release Date"
      description: "Enter the target release date."
      placeholder: "Enter target date"

  # Release Status Field
  - type: checkboxes
    attributes:
      label: "Release Status"
      description: "Select the current release status."
      options:
        - label: "Draft"
        - label: "Open"
        - label: "Complete"
        - label: "Cancelled"

  # Activities/Tasks
  ### 1) Create Rally Milestone and ServiceNow Release
  - type: input
    attributes:
      label: "Assigned to (Rally Milestone)"
      description: "Enter the GitHub username of the person assigned to this task."
      placeholder: "Enter GitHub username"
  - type: checkboxes
    attributes:
      label: "Status (Rally Milestone)"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"

  ### 2) QA Sign Off
  - type: input
    attributes:
      label: "Assigned to (QA Sign Off)"
      description: "Enter the GitHub username of the person assigned to this task."
      placeholder: "Enter GitHub username"
  - type: checkboxes
    attributes:
      label: "Status (QA Sign Off)"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"

  ### 3) SRE Signoff
  - type: input
    attributes:
      label: "Assigned to (SRE Signoff)"
      description: "Enter the GitHub username of the person assigned to this task."
      placeholder: "Enter GitHub username"
  - type: checkboxes
    attributes:
      label: "Status (SRE Signoff)"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"

  ### 4) App Owner Approval
  - type: input
    attributes:
      label: "Assigned to (App Owner Approval)"
      description: "Enter the GitHub username of the person assigned to this task."
      placeholder: "Enter GitHub username"
  - type: checkboxes
    attributes:
      label: "Status (App Owner Approval)"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"
