name: "Release Milestone"
description: "Template for creating a release milestone with tasks and statuses"
labels:
  - "release-milestone"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Release Milestone
        - **Release Milestone**: [Enter milestone name]
        - **Application**: [Enter application name]
        - **Target Date**: [Enter target release date]

        ## Activities & Tasks:

        ### 1) Create Rally milestone and ServiceNow Release:
        - **Assigned to**: [Assign person]
        - **Status**: [Complete/In Progress/NA]

        ### 2) QA Sign Off:
        - **Assigned to**: [Assign person]
        - **Status**: [Complete/In Progress/NA]

        ### 3) SRE Signoff:
        - **Assigned to**: [Assign person]
        - **Status**: [Complete/In Progress/NA]

        ### 4) App Owner Approval:
        - **Assigned to**: [Assign person]
        - **Status**: [Complete/In Progress/NA]

        ### Checklist:
        - [ ] Task 1 Completed
        - [ ] Task 2 Completed
        - [ ] Task 3 Completed
        - [ ] Task 4 Completed
