name: "Release Milestone"
description: "Template for creating a release milestone with tasks and statuses"
labels:
  - "release-milestone"
assignees: []
body:
  - type: input
    attributes:
      label: "Release Milestone"
      description: "Enter the release milestone name."
      placeholder: "Enter milestone name"
      
  - type: input
    attributes:
      label: "Application"
      description: "Enter the name of the application."
      placeholder: "Enter application name"
      
  - type: input
    attributes:
      label: "Target Date"
      description: "Enter the target release date."
      placeholder: "Enter target release date"
      
  - type: textarea
    attributes:
      label: "Release Notes"
      description: "Provide any additional details or release notes."
      placeholder: "Enter release notes here..."
      
  - type: dropdown
    attributes:
      label: "Status"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"
      
  - type: checkboxes
    attributes:
      label: "Release Checklist"
      options:
        - label: "Task 1 Completed"
        - label: "Task 2 Completed"
        - label: "Task 3 Completed"
        - label: "Task 4 Completed"
