yaml
name: Release Record Template
description: Template for tracking release activities.
labels:
  - release
body:
  - type: markdown
    value: |
      ### Release Details
      _Please fill out the details for this release below._
      
      **Application Name:**  
      _Enter the name of the application._
      
      **Release Version:**  
      _Enter the version number (e.g., v1.0.0)._

  - type: checkbox
    label: Pre-release Steps
    description: 'Please confirm the following pre-release steps have been completed.'
    required: true
    options:
      - 'Build successfully created'
      - 'QA sign-off completed'
      - 'UAT sign-off completed'
