name: "Release Milestone"
description: "Template for creating a release milestone with tasks and statuses"
labels:
  - "release-milestone"
assignees: []
body:
  # Markdown body section for task description
  - type: markdown
    attributes:
      value: |
        ## Release Milestone
        - **Release Milestone**: [Enter milestone name]
        - **Application**: [Enter application name]
        - **Target Date**: [Enter target release date]

        ## Activities & Tasks:

        ### 1) Create Rally milestone and ServiceNow Release:
        - **Assigned to**: [Enter the name of the person responsible]
        - **Status**: [Complete/In Progress/NA]

        ### 2) QA Sign Off:
        - **Assigned to**: [Enter the name of the person responsible]
        - **Status**: [Complete/In Progress/NA]

        ### 3) SRE Signoff:
        - **Assigned to**: [Enter the name of the person responsible]
        - **Status**: [Complete/In Progress/NA]

        ### 4) App Owner Approval:
        - **Assigned to**: [Enter the name of the person responsible]
        - **Status**: [Complete/In Progress/NA]

  # Non-markdown field: Text input for "Assigned to"
  - type: input
    attributes:
      label: "Assigned to"
      description: "Enter the name of the person assigned to this task."
      placeholder: "Enter the person's name"

  # Non-markdown field: Dropdown-like options for "Status"
  - type: checkboxes
    attributes:
      label: "Status"
      options:
        - label: "Complete"
        - label: "In Progress"
        - label: "NA"
