yaml

name: Simple Release Record
description: 'Basic template for tracking release activities.'
labels:
  - release
  - simple
body:
  - type: markdown
    value: |
      ### Release Details
      _Please provide the details for the release below._
      
      **Application Name**:  
      _Enter the name of the application._
      
      **Release Version**:  
      _Enter the release version (e.g., v1.0.0)._

  - type: checklist
    label: Pre-release Steps
    description: 'Confirm the pre-release steps have been completed.'
    required: true
    options:
      - 'Build successfully created'
      - 'QA sign-off completed'
      - 'UAT sign-off completed'
