yaml
description: Template for tracking release activities.
labels:
  - release
  - simple
body:
  - type: markdown
    value: |
      ### Release Details
      _Please fill out the details for this release below._
      
      **Application Name:**  
      _Enter the name of the application._
      
      **Release Version:**  
      _Enter the version number (e.g., v1.0.0)._

  - type: checklist
    label: Pre-release Steps
    description: 'Please check the items below as you complete each pre-release step.'
    required: true
    options:
      - 'Build successfully created'
      - 'QA sign-off completed'
      - 'UAT sign-off completed'


