yaml

name: "Simple Release Pipeline"

on:
  pull_request:
    branches:
      - main      # You can change to your target branch
  workflow_dispatch:  # Allows you to trigger this manually

jobs:
  build:
    runs-on: ubuntu-latest  # This can be changed to any environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use your preferred Node.js version

      - name: Install Dependencies (if applicable)
        run: npm install

      - name: Run Tests (if applicable)
        run: npm test  # You can change this if you use other testing tools

  approval:
    needs: build  # Ensure that approval only happens after a successful build
    runs-on: ubuntu-latest
    if: success()  # Ensure this only runs if 'build' job was successful

    steps:
      - name: Approval Step
        run: echo "Waiting for approval..."
        continue-on-error: true  # This will allow manual intervention to continue

  deploy:
    needs: approval
    runs-on: ubuntu-latest
    environment: production  # The name of the environment in GitHub
    if: success()  # Ensure this only runs if 'approval' is successful

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: echo "Deploying to production..."
        # Add your deployment commands here (e.g., AWS, Azure, etc.)

